import {createContext,useContext,useState,useCallback} from 'react';import {X,CheckCircle2,AlertCircle,Inbox} from 'lucide-react';
export const cx=(...a)=>a.filter(Boolean).join(' ');
export const inp='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm placeholder:text-slate-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-100';
export const Card=({className,...p})=><div className={cx('rounded-xl border border-slate-200 bg-white shadow-sm',className)} {...p}/>;
export const Button=({variant='primary',className,...p})=><button className={cx('inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:opacity-50',variant==='primary'&&'bg-indigo-600 text-white shadow-sm hover:bg-indigo-700',variant==='ghost'&&'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50',variant==='danger'&&'bg-red-600 text-white hover:bg-red-700',className)} {...p}/>;
const tone={Active:'green',Processed:'green',Upcoming:'amber',Scheduled:'amber',Pending:'amber',Failed:'red',Completed:'indigo'};
const tones={green:'bg-green-50 text-green-700',amber:'bg-amber-50 text-amber-700',red:'bg-red-50 text-red-700',indigo:'bg-indigo-50 text-indigo-700',slate:'bg-slate-100 text-slate-600'};
export const Badge=({children})=><span className={cx('rounded-full px-2.5 py-0.5 text-xs font-medium',tones[tone[children]||'slate'])}>{children}</span>;
export const Skeleton=({className})=><div className={cx('h-10 animate-pulse rounded-lg bg-slate-100',className)}/>;
export const Empty=({text,sub,icon:I=Inbox})=><Card className="flex flex-col items-center gap-2 px-6 py-14 text-center"><div className="rounded-full bg-slate-100 p-3 text-slate-400"><I size={22}/></div><p className="font-medium text-slate-700">{text}</p>{sub&&<p className="text-sm text-slate-500">{sub}</p>}</Card>;
export const Modal=({title,onClose,children})=><div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4" onClick={onClose}><Card className="pop max-h-[90vh] w-full max-w-lg overflow-y-auto p-6" onClick={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2><button aria-label="Close" onClick={onClose} className="text-slate-400 hover:text-slate-700"><X size={18}/></button></div>{children}</Card></div>;
export const StatCard=({icon:I,label,value})=><Card className="flex items-center gap-4 p-5"><div className="rounded-lg bg-indigo-50 p-3 text-indigo-600"><I size={22}/></div><div><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-semibold">{value}</p></div></Card>;
const T=createContext();export const useToast=()=>useContext(T);
export function ToastProvider({children}){const [l,set]=useState([]);
const push=useCallback((msg,type='ok')=>{const id=Math.random();set(a=>[...a,{id,msg,type}]);setTimeout(()=>set(a=>a.filter(x=>x.id!==id)),3500)},[]);
return <T.Provider value={push}>{children}<div className="fixed bottom-4 right-4 z-[60] space-y-2">{l.map(t=><div key={t.id} className={cx('pop flex items-center gap-2 rounded-lg px-4 py-3 text-sm text-white shadow-lg',t.type==='ok'?'bg-slate-900':'bg-red-600')}>{t.type==='ok'?<CheckCircle2 size={16}/>:<AlertCircle size={16}/>}{t.msg}</div>)}</div></T.Provider>}
