import {useState} from 'react';import {useNavigate} from 'react-router-dom';import {Sparkles,Send,RefreshCw,Save,Bot} from 'lucide-react';import api,{errMsg} from '../services/api';import {Card,Button,Badge,inp,cx,useToast} from '../components/ui';import {SPORTS,FORMATS} from './Resources';
const init={sport:'Cricket',teams:8,format:'Knockout',startDate:'',endDate:'',grounds:2,matchDuration:90,restTime:15,venue:'',special:''};
const L=({l,children,wide})=><label className={cx('text-sm font-medium text-slate-700',wide&&'sm:col-span-2 lg:col-span-3')}>{l}<div className="mt-1">{children}</div></label>;
function Generator(){const toast=useToast(),nav=useNavigate(),[f,setF]=useState(init),[plan,setPlan]=useState(),[busy,setBusy]=useState(false),[err,setErr]=useState();
const set=k=>e=>setF({...f,[k]:e.target.value}),gen=async e=>{e?.preventDefault();setBusy(true);setErr();try{setPlan((await api.post('/ai/generate-plan',f)).data.plan)}catch(x){setErr(errMsg(x))}setBusy(false)};
const save=async()=>{try{await api.post('/ai/save-plan',{plan,input:f});toast('Tournament saved as a draft');nav('/tournaments')}catch(x){toast(errMsg(x),'err')}};
const grounds={};plan?.matches.forEach(m=>grounds[m.ground]=(grounds[m.ground]||0)+1);
return <div className="space-y-6"><Card className="p-6"><form onSubmit={gen} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
<L l="Sport"><select className={inp} value={f.sport} onChange={set('sport')}>{SPORTS.map(s=><option key={s}>{s}</option>)}</select></L>
<L l="Number of teams"><input className={inp} type="number" min="2" max="64" required value={f.teams} onChange={set('teams')}/></L>
<L l="Format"><select className={inp} value={f.format} onChange={set('format')}>{FORMATS.map(s=><option key={s}>{s}</option>)}</select></L>
<L l="Start date"><input className={inp} type="date" required value={f.startDate} onChange={set('startDate')}/></L><L l="End date"><input className={inp} type="date" value={f.endDate} onChange={set('endDate')}/></L>
<L l="Venue"><input className={inp} value={f.venue} onChange={set('venue')}/></L>
<L l="Grounds"><input className={inp} type="number" min="1" value={f.grounds} onChange={set('grounds')}/></L><L l="Match duration (min)"><input className={inp} type="number" min="10" value={f.matchDuration} onChange={set('matchDuration')}/></L><L l="Rest time (min)"><input className={inp} type="number" min="0" value={f.restTime} onChange={set('restTime')}/></L>
<L l="Special requirements" wide><textarea rows={2} className={inp} placeholder="e.g. No matches on Sunday, floodlights unavailable" value={f.special} onChange={set('special')}/></L>
<div className="sm:col-span-2 lg:col-span-3"><Button disabled={busy} className="w-full py-3 sm:w-auto"><Sparkles size={16}/>{busy?'Generating plan':'Generate Tournament Plan'}</Button></div></form></Card>
{err&&<p className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{err}</p>}
{plan&&<div className="space-y-4"><Card className="p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="mb-2 inline-block rounded-full bg-amber-50 px-2.5 py-0.5 text-xs font-medium text-amber-700">Demo output: mock AI, no LLM connected</span><h2 className="text-xl font-semibold">{plan.tournamentName}</h2><p className="mt-1 text-sm text-slate-600">{plan.summary}</p></div>
<div className="flex gap-2"><Button variant="ghost" onClick={gen} disabled={busy}><RefreshCw size={16}/>Regenerate</Button><Button onClick={save}><Save size={16}/>Save as Tournament</Button></div></div>
<div className="mt-4 flex flex-wrap gap-2 text-sm"><Badge>{plan.format}</Badge>{Object.entries(grounds).map(([g,n])=><span key={g} className="rounded-full bg-slate-100 px-2.5 py-0.5 text-xs text-slate-600">{g}: {n} matches</span>)}</div></Card>
<div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h3 className="mb-2 font-semibold">Rules</h3><ol className="list-decimal space-y-1.5 pl-5 text-sm text-slate-600">{plan.rules.map(r=><li key={r}>{r}</li>)}</ol></Card><Card className="p-5"><h3 className="mb-2 font-semibold">Recommendations</h3><ul className="list-disc space-y-1.5 pl-5 text-sm text-slate-600">{plan.recommendations.map(r=><li key={r}>{r}</li>)}</ul></Card></div>
<Card className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs text-slate-500"><tr>{['Round','Match','Date','Time','Ground'].map(h=><th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{plan.matches.map((m,i)=><tr key={i}><td className="px-4 py-2.5">{m.round}</td><td className="whitespace-nowrap px-4 py-2.5 font-medium">{m.team1} vs {m.team2}</td><td className="px-4 py-2.5">{m.date}</td><td className="px-4 py-2.5">{m.time}</td><td className="px-4 py-2.5">{m.ground}</td></tr>)}</tbody></table></Card></div>}</div>}
const chips=['Create a knockout tournament for 8 cricket teams','Generate a schedule for 16 football teams','What format should I use for 12 teams?','Create rules for a university cricket tournament'];
function Assistant(){const [msgs,setMsgs]=useState([]),[t,setT]=useState(''),[busy,setBusy]=useState(false);
const send=async text=>{if(!text.trim()||busy)return;setMsgs(m=>[...m,{r:'u',t:text}]);setT('');setBusy(true);let reply;try{reply=(await api.post('/ai/chat',{message:text})).data.reply}catch(x){reply=errMsg(x)}setMsgs(m=>[...m,{r:'a',t:reply}]);setBusy(false)};
return <Card className="flex h-[70vh] flex-col"><div className="flex items-center gap-3 border-b border-slate-200 p-4"><div className="rounded-lg bg-indigo-50 p-2 text-indigo-600"><Bot size={20}/></div><div><h2 className="font-semibold">AI Tournament Assistant</h2><p className="text-xs text-amber-700">Demo replies: no LLM connected</p></div></div>
<div className="flex-1 space-y-3 overflow-y-auto p-4">{!msgs.length&&<div className="grid gap-2 sm:grid-cols-2">{chips.map(c=><button key={c} onClick={()=>send(c)} className="rounded-lg border border-slate-200 p-3 text-left text-sm text-slate-600 transition hover:border-indigo-300 hover:bg-indigo-50">{c}</button>)}</div>}
{msgs.map((m,i)=><div key={i} className={cx('flex',m.r==='u'&&'justify-end')}><p className={cx('max-w-[85%] whitespace-pre-wrap rounded-2xl px-4 py-2.5 text-sm',m.r==='u'?'bg-indigo-600 text-white':'bg-slate-100')}>{m.t}</p></div>)}{busy&&<p className="text-sm text-slate-400">Thinking</p>}</div>
<form className="flex gap-2 border-t border-slate-200 p-3" onSubmit={e=>{e.preventDefault();send(t)}}><input className={inp} placeholder="Ask about formats, schedules or rules" value={t} onChange={e=>setT(e.target.value)}/><Button aria-label="Send" disabled={busy}><Send size={16}/></Button></form></Card>}
export default function AIStudio(){const [tab,setTab]=useState('Plan Generator');
return <div className="space-y-5"><div className="inline-flex rounded-lg border border-slate-200 bg-white p-1 text-sm">{['Plan Generator','Assistant'].map(x=><button key={x} onClick={()=>setTab(x)} className={cx('rounded-md px-4 py-1.5 font-medium transition',tab===x?'bg-indigo-600 text-white':'text-slate-600 hover:bg-slate-50')}>{x}</button>)}</div>{tab==='Assistant'?<Assistant/>:<Generator/>}</div>}
