import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {Trophy,Activity,Users,CalendarClock,Sparkles} from 'lucide-react';import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,Legend} from 'recharts';import api,{errMsg} from '../services/api';import {Card,Badge,Skeleton,Empty,StatCard,Button} from '../components/ui';
const C=['#4F46E5','#818CF8','#A5B4FC','#C7D2FE','#6366F1'];
export default function Dashboard(){const [d,setD]=useState(),[err,setErr]=useState();useEffect(()=>{api.get('/dashboard/stats').then(r=>setD(r.data)).catch(e=>setErr(errMsg(e)))},[]);
if(err)return <Empty text="Could not load the dashboard" sub={err}/>;
if(!d)return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map(i=><Skeleton key={i} className="h-24"/>)}</div>;
const t=d.totals;
return <div className="space-y-6">
<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard icon={Trophy} label="Total Tournaments" value={t.tournaments}/><StatCard icon={Activity} label="Active Tournaments" value={t.active}/><StatCard icon={Users} label="Total Teams" value={t.teams}/><StatCard icon={CalendarClock} label="Upcoming Matches" value={t.upcoming}/></div>
<Card className="flex flex-wrap items-center justify-between gap-4 border-indigo-100 bg-indigo-50 p-5"><div className="flex items-center gap-3"><Sparkles className="text-indigo-600"/><div><p className="font-semibold">Try the AI Planner</p><p className="text-sm text-slate-600">Describe your event and get fixtures, a schedule and rules in seconds.</p></div></div><Link to="/ai"><Button>Generate a plan</Button></Link></Card>
<div className="grid gap-6 lg:grid-cols-2">
<Card className="p-5"><h3 className="mb-4 font-semibold">Tournaments by sport</h3><div className="h-56"><ResponsiveContainer><BarChart data={d.bySport}><XAxis dataKey="name" fontSize={12} tickLine={false}/><YAxis allowDecimals={false} fontSize={12} tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="value" name="Tournaments" fill="#4F46E5" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></Card>
<Card className="p-5"><h3 className="mb-4 font-semibold">Tournaments by status</h3><div className="h-56"><ResponsiveContainer><PieChart><Pie data={d.byStatus} dataKey="value" innerRadius={50} outerRadius={80}>{d.byStatus.map((_,i)=><Cell key={i} fill={C[i%C.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></Card></div>
<div className="grid gap-6 lg:grid-cols-2">
<Card className="p-5"><h3 className="mb-3 font-semibold">Recent tournaments</h3><ul className="divide-y divide-slate-100">{d.recent.map(x=><li key={x.id} className="flex items-center justify-between py-3 text-sm"><div><p className="font-medium">{x.name}</p><p className="text-slate-500">{x.sport} · {x.format}</p></div><Badge>{x.status}</Badge></li>)}</ul></Card>
<Card className="p-5"><h3 className="mb-3 font-semibold">Upcoming matches</h3>{d.upcoming.length?<ul className="divide-y divide-slate-100">{d.upcoming.map(m=><li key={m.id} className="py-3 text-sm"><p className="font-medium">{m.team1} vs {m.team2}</p><p className="text-slate-500">{m.Tournament?.name} · {m.round} · {m.date} {m.time}</p></li>)}</ul>:<p className="py-6 text-center text-sm text-slate-500">No upcoming matches. Add fixtures to see them here.</p>}</Card></div></div>}
