import {useEffect,useState,useRef} from 'react';import {UploadCloud,Trash2,FileText,Search} from 'lucide-react';import api,{errMsg} from '../services/api';import {Card,Badge,Skeleton,Empty,inp,cx,useToast,Button} from '../components/ui';import {SPORTS} from './Resources';
export default function Knowledge(){const toast=useToast(),ref=useRef(),[docs,setDocs]=useState(),[q,setQ]=useState(''),[sport,setSport]=useState('General'),[cat,setCat]=useState('Rules'),[drag,setDrag]=useState(false),[busy,setBusy]=useState(false);
const load=()=>api.get('/documents').then(r=>setDocs(r.data)).catch(e=>toast(errMsg(e),'err'));useEffect(()=>{load()},[]);
const upload=async file=>{if(!file)return;if(!/\.(pdf|txt|docx)$/i.test(file.name))return toast('Only PDF, TXT and DOCX files are allowed','err');const fd=new FormData();fd.append('sport',sport);fd.append('category',cat);fd.append('file',file);setBusy(true);
try{await api.post('/documents/upload',fd);toast('Document uploaded');load()}catch(e){toast(errMsg(e),'err')}setBusy(false)};
const remove=async d=>{try{await api.delete(`/documents/${d.id}`);toast('Document deleted');load()}catch(e){toast(errMsg(e),'err')}};
const shown=docs?.filter(d=>(d.name+d.sport+d.category).toLowerCase().includes(q.toLowerCase()));
return <div className="space-y-5"><Card className="p-5"><div className="mb-4 flex flex-wrap gap-3"><select className={cx(inp,'w-40')} value={sport} onChange={e=>setSport(e.target.value)}>{['General',...SPORTS].map(s=><option key={s}>{s}</option>)}</select><select className={cx(inp,'w-40')} value={cat} onChange={e=>setCat(e.target.value)}>{['Rules','Regulations','Schedule guide','Other'].map(s=><option key={s}>{s}</option>)}</select></div>
<div onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);upload(e.dataTransfer.files[0])}} className={cx('flex flex-col items-center gap-2 rounded-xl border-2 border-dashed p-10 text-center transition',drag?'border-indigo-500 bg-indigo-50':'border-slate-300')}>
<UploadCloud className="text-slate-400" size={28}/><p className="text-sm text-slate-600">{busy?'Uploading':'Drag a rulebook here, or'}</p><input ref={ref} type="file" accept=".pdf,.txt,.docx" hidden onChange={e=>{upload(e.target.files[0]);e.target.value=''}}/><Button variant="ghost" disabled={busy} onClick={()=>ref.current.click()}>Choose file</Button><p className="text-xs text-slate-400">PDF, TXT or DOCX, up to 10 MB. Processing starts once RAG is connected.</p></div></Card>
<div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input className={cx(inp,'pl-9')} placeholder="Search documents" value={q} onChange={e=>setQ(e.target.value)}/></div>
{!docs?<Card className="space-y-3 p-4">{[1,2,3].map(i=><Skeleton key={i}/>)}</Card>:!shown.length?<Empty icon={FileText} text="No documents yet" sub="Upload a rulebook to build your knowledge base."/>:
<Card className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs text-slate-500"><tr>{['Name','Sport','Category','Uploaded','Status',''].map(h=><th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{shown.map(d=><tr key={d.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-medium">{d.name}</td><td className="px-4 py-3">{d.sport}</td><td className="px-4 py-3">{d.category}</td><td className="whitespace-nowrap px-4 py-3">{new Date(d.createdAt).toLocaleDateString()}</td><td className="px-4 py-3"><Badge>{d.status}</Badge></td><td className="px-4 py-3 text-right"><button aria-label="Delete" onClick={()=>remove(d)} className="rounded p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={16}/></button></td></tr>)}</tbody></table></Card>}</div>}
