import CrudPage from '../components/CrudPage';import {Badge,Card} from '../components/ui';
export const SPORTS=['Cricket','Football','Basketball','Volleyball','Badminton','Tennis','Kabaddi','Custom'],FORMATS=['Knockout','Round Robin','Group + Knockout'];
const S={key:'status',label:'Status',render:r=><Badge>{r.status}</Badge>};
const st=o=>({key:'status',label:'Status',options:o});
export const Tournaments=()=><CrudPage title="Tournaments" noun="Tournament" path="/tournaments"
cols={[{key:'name',label:'Name'},{key:'sport',label:'Sport'},{key:'format',label:'Format'},{key:'numTeams',label:'Teams'},{key:'startDate',label:'Starts'},{key:'venue',label:'Venue'},S]}
fields={[{key:'name',label:'Tournament name',req:1,wide:1},{key:'sport',label:'Sport',options:SPORTS,req:1},{key:'format',label:'Format',options:FORMATS,req:1},{key:'numTeams',label:'Number of teams',type:'number'},{key:'venue',label:'Venue'},{key:'startDate',label:'Start date',type:'date'},{key:'endDate',label:'End date',type:'date'},{key:'grounds',label:'Grounds',type:'number'},{key:'matchDuration',label:'Match duration (min)',type:'number'},{key:'restTime',label:'Rest time (min)',type:'number'},st(['Draft','Upcoming','Active','Completed']),{key:'description',label:'Description',type:'textarea',wide:1}]}/>;
export const Teams=()=><CrudPage title="Teams" noun="Team" path="/teams"
cols={[{key:'name',label:'Team'},{key:'sport',label:'Sport'},{key:'captain',label:'Captain'},{key:'coach',label:'Coach'},S]}
fields={[{key:'name',label:'Team name',req:1,wide:1},{key:'sport',label:'Sport',options:SPORTS},st(['Active','Inactive']),{key:'captain',label:'Captain'},{key:'coach',label:'Coach'}]}/>;
export const Players=()=><CrudPage title="Players" noun="Player" path="/players"
cols={[{key:'name',label:'Player'},{key:'team',label:'Team',render:r=>r.Team?.name},{key:'jersey',label:'Jersey #'},{key:'position',label:'Position'},{key:'age',label:'Age'},{key:'contact',label:'Contact'},S]}
fields={[{key:'name',label:'Player name',req:1,wide:1},{key:'teamId',label:'Team',ref:'/teams',valueKey:'id'},{key:'position',label:'Position'},{key:'age',label:'Age',type:'number'},{key:'jersey',label:'Jersey number',type:'number'},{key:'contact',label:'Contact'},st(['Active','Inactive'])]}/>;
const Bracket=rows=>{const by={};rows.slice().reverse().forEach(m=>{const t=m.Tournament?.name||'Unassigned';(by[t]??={});(by[t][m.round]??=[]).push(m)});
return <div className="space-y-8">{Object.entries(by).map(([t,rounds])=><div key={t}><h3 className="mb-3 font-semibold">{t}</h3><div className="flex gap-6 overflow-x-auto pb-3">{Object.entries(rounds).map(([r,ms])=><div key={r} className="flex min-w-[230px] flex-col justify-around gap-3"><p className="text-sm font-medium text-slate-500">{r}</p>
{ms.map(m=><Card key={m.id} className="divide-y divide-slate-100 text-sm"><div className="px-3 py-2">{m.team1||'TBD'}</div><div className="px-3 py-2">{m.team2||'TBD'}</div><div className="flex justify-between rounded-b-xl bg-slate-50 px-3 py-1.5 text-xs text-slate-500"><span>{m.date} {m.time}</span><Badge>{m.status}</Badge></div></Card>)}</div>)}</div></div>)}</div>};
export const Fixtures=()=><CrudPage title="Fixtures" noun="Match" path="/matches" alt={{key:'bracket',render:Bracket}}
cols={[{key:'t',label:'Tournament',render:r=>r.Tournament?.name},{key:'round',label:'Round'},{key:'m',label:'Match',render:r=><b className="font-medium">{r.team1||'TBD'} vs {r.team2||'TBD'}</b>},{key:'date',label:'Date'},{key:'time',label:'Time'},{key:'ground',label:'Ground'},S,{key:'result',label:'Result'}]}
fields={[{key:'tournamentId',label:'Tournament',ref:'/tournaments',valueKey:'id',req:1,wide:1},{key:'round',label:'Round',req:1},st(['Scheduled','Live','Completed']),{key:'team1',label:'Team 1',ref:'/teams',valueKey:'name'},{key:'team2',label:'Team 2',ref:'/teams',valueKey:'name'},{key:'date',label:'Date',type:'date'},{key:'time',label:'Time',type:'time'},{key:'ground',label:'Ground'},{key:'venue',label:'Venue'},{key:'result',label:'Result',wide:1}]}/>;
